name: Δοκιμή Secret

on: push

jobs:
  secret-test:
    runs-on: ubuntu-latest
    steps:
      - name: Προσπάθεια χρήσης μη ορισμένου secret
        run: echo "Χρησιμοποιώ το API KEY: ${{ secrets.API_KEY }}"
